name: 19 - Managing Concurrency

on:
    workflow_dispatch:

jobs:
    ping:
        runs-on: ubuntu-latest
        concurrency:
            group: ping-${{ github.ref }}
            cancel-in-progress: true
        steps:
            - uses: actions/checkout@v4
            - name: Ping URL            
              run: |
                  echo "Pinging..."
                  sleep 10
                  echo "Done!"
    